### ISSUE TITLE
Next major version: code cleanup, return types, Symfony 6...

### ISSUE THREAD

**Issue by jmsche** [leapt/im-bundle#1]
As Symfony 6 may add return types, it will also require a new major version.

It's the perfect time to also add return types everywhere it's possible. Maybe even add a constraint in code analyzers about it?

The new major version _should_ be released in November or early December, so phpstan will also be available as 1.x version.

To do:

- [x] Clean up code (remove useless comments, add return types, constructor property promotion...) => #7 
- [x] Improve Phpstan level? (optional) => #8 
- [x] Support Symfony 6 => #4 
- [x] Drop Symfony 4.x support => #5 
- [x] Drop PHP < 8.0 support => #3 
- [x] Create a 4.x branch
- [x] Declare strict types everywhere? (optional) => #6 
- [x] Upgrade phpstan to 1.0 (expected release: November, 1st) => #9 
- [x] Migrate the existing annotation to a PHP attribute (only) => #10 
- [x] Update README => #13 
- [x] Make docs using mkdocs-material, update them & build them on Github pages => #11 
- [x] Add .gitattributes => #14 
- [x] Set min Symfony version to 5.4 => #15

**Comment by jmsche** [comment]
v4.0.0 released :)
